### ISSUE TITLE
Reload Views 

### ISSUE THREAD

**Issue by utkuerturk** [ikhsan/IAInfiniteGridView#6]
Is there any methot to reload views . Like [tableView reloadData];

**Comment by rayshih** [comment]
After look into source code, I currently use this method to achieve this.

```
[self.gridView awakeFromNib];
[self.gridView jumpToIndex:0];
```

**Comment by ikhsan** [comment]
Just added the method, the implementation is similar to [rayshish](https://github.com/rayshih)'s

``` objective-c
- (void)reloadData;
```
