### ISSUE TITLE
Adding Programmatically

### ISSUE THREAD

**Issue by JohnnySlagle** [ikhsan/IAInfiniteGridView#7]
I cannot figure out how to setup and add a IAInfiniteGridView programmatically.  Am I doing anything wrong?

``` Objective-C
IAInfiniteGridView *gridView = [[IAInfiniteGridView alloc] initWithFrame:CGRectMake(0.0, 0.0, 320.0, 568.0f)];
    gridView.paging = YES;

    gridView.hidden = NO;
    gridView.dataSource = self;
    gridView.gridDelegate = self;

    self.gridView = gridView;

    [self.view addSubview:self.gridView];
```

**Comment by l4u** [comment]
awakeFromNib isn't called.
https://github.com/ixnixnixn/IAInfiniteGridView/blob/0ecd6495d707e2310fa944e8c4c2bb009f533fef/IAInfiniteGridView/IAInfiniteGridView.m#L55-L61

As a workaround, the ScrollView content size and containerView.frame should be updated (with a newly created public method probably).

**Comment by ikhsan** [comment]
I've fix this by firing calculate content size in datasource's setter method
