### ISSUE TITLE
content size (5x views size)

### ISSUE THREAD

**Issue by fvisticot** [ikhsan/IAInfiniteGridView#9]
Why is scrollview content size 5 times bigger compared to the number of elements part of the scrolling view ?

self.contentSize = CGSizeMake(5 \* totalGrids \* gridSize.width, gridSize.height);

**Comment by tudormunteanu** [comment]
Strange. I see this too.

**Comment by ikhsan** [comment]
I've deleted the multiplier and it works fine now. My first thought is the scrollview need much bigger contentSize. Turns out that's not the case. Thanks for the code review.

**Comment by ikhsan** [comment]
After some tests for edge cases, it should be bigger that total grids's size. But multiplying by 2 would suffice.
